theme: jekyll-theme-dinky
title: Christopher D'Agostino
description: Welcome to my homepage! My projects this semester will highlight current issues and events that are effecting the world or topics that personally resonate with me.  Bookmark my page to watch out for new and updated projects.  
