theme: jekyll-theme-cayman
title: Christopher D'Agostino
description: Welcome to my homepage! My data visualization projects this semester will highlight current issues and events that are affecting the world or topics that personally resonate with me.  Bookmark my page to watch out for new and updated projects.  
